name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator symbiyosys python3-venv python3-pip

      - name: Install OSS CAD Suite
        run: |
          curl -L https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-12-05/oss-cad-suite-linux-x64-20241205.tgz -o oss-cad-suite.tgz
          tar -xzf oss-cad-suite.tgz
          echo "OSS_CAD_SUITE=${GITHUB_WORKSPACE}/oss-cad-suite" >> $GITHUB_ENV
          echo "YOSYS_SV_BIN=${GITHUB_WORKSPACE}/oss-cad-suite/bin/yosys" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/oss-cad-suite/bin" >> $GITHUB_PATH

      - name: Tool env
        run: make env

      - name: Lint
        run: make lint

      - name: Check (seeded)
        run: make check SEED=${{ github.run_id }}

      - name: Synthesis
        run: make synth

      - name: Formal (prove)
        run: make formal_all

      - name: Dashboards & Badge
        run: |
          make dashboards
          make badge

      - name: JUnit + Artifacts
        run: make junit

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/

      - name: Publish site
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/site
