name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install EDA toolchain
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y verilator jq python3-venv python3-pip

          curl -L \
            https://github.com/YosysHQ/oss-cad-suite-build/releases/latest/download/oss-cad-suite-linux-x64.tar.xz \
            -o /tmp/oss-cad-suite.tar.xz
          mkdir -p "$GITHUB_WORKSPACE/oss-cad-suite"
          tar -xJf /tmp/oss-cad-suite.tar.xz -C "$GITHUB_WORKSPACE/oss-cad-suite" --strip-components=1

          echo "$GITHUB_WORKSPACE/oss-cad-suite/bin" >> $GITHUB_PATH
          echo "OSS_CAD_SUITE=$GITHUB_WORKSPACE/oss-cad-suite" >> $GITHUB_ENV
          echo "YOSYS_SV_BIN=$GITHUB_WORKSPACE/oss-cad-suite/bin/yosys" >> $GITHUB_ENV
          echo "SBY_BIN=$GITHUB_WORKSPACE/oss-cad-suite/bin/sby" >> $GITHUB_ENV

      - name: Smoke-check tools
        run: |
          set -euxo pipefail
          verilator --version
          "$YOSYS_SV_BIN" -V | head -n1
          "$SBY_BIN" --help | head -n1

      - name: Tool env
        run: make env

      - name: Lint
        run: make lint

      - name: Check (seeded)
        run: make check SEED=${{ github.run_id }}

      - name: Synthesis
        run: make synth

      - name: Formal (prove)
        run: make formal_all

      - name: Dashboards & Badge
        run: |
          make dashboards
          make badge

      - name: JUnit + Artifacts
        run: make junit

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/

      - name: Publish site
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/site
